on: [push, pull_request]

name: 'Analyse shell scripts'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck on root 
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './archiso/airootfs/root'
        ignore_names: .automated_script.sh .zlogin
      env:
        SHELLCHECK_OPTS: -x
    - name: Run ShellCheck on usr/local/bin
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './archiso/airootfs/usr/local/bin'
        ignore_names: 'choose-mirror'
      env:
        SHELLCHECK_OPTS: -x
